# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-12-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181226_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
