# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_a', '0006_auto_20170715_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='IP_host',
            new_name='Author',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='ip',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='admin_a.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish', to='admin_a.Publish'),
        ),
    ]
